services:
  bookly-frontend:
    build: ./frontend
    depends_on:
      - bookly-backend-app
    container_name: bookly-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  bookly-backend-app:
    build: ./backend
    depends_on:
      - database
    container_name: bookly-backend-app
    ports:
      - "8000:80"
    restart: unless-stopped
    command: >
      sh -c "
        while ! mysqladmin ping -hdatabase --silent; do
          sleep 1;
        done;
        php artisan migrate --force &&
        apache2-foreground
      "

  database:
    image: mysql:8.0
    container_name: bookly-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bookstore
      MYSQL_USER: ali
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmina
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - database
